// Generated, do not edit.
#include <stdio.h>
#include <stddef.h>
#include "gumbo.h"

int main () {
	printf("(* Generated, do not edit. *)\n");
	printf("structure GumboConstants =\n");
	printf("struct\n");
	printf("  open GumboCommon\n");

	printf("  val offsetof_ActualNodeData = %zu\n", offsetof(struct GumboInternalNode, v));
	printf("  val offsetof_ElementTag = %zu\n", offsetof(GumboElement, tag));
	printf("  val offsetof_ElementAttributes = %zu\n", offsetof(GumboElement, attributes));
	printf("  val offsetof_GumboSourcePosition = %zu\n", offsetof(GumboElement, start_pos));
	printf("  val offsetof_GumboAttributeName = %zu\n", offsetof(GumboAttribute, name));
	printf("  val offsetof_GumboAttributeValue = %zu\n", offsetof(GumboAttribute, value));

	printf("  fun nodeTypeFromInt %i = NodeDocument\n", GUMBO_NODE_DOCUMENT);
	printf("    | nodeTypeFromInt %i = NodeElement\n", GUMBO_NODE_ELEMENT);
	printf("    | nodeTypeFromInt %i = NodeText\n", GUMBO_NODE_TEXT);
	printf("    | nodeTypeFromInt %i = NodeCdata\n", GUMBO_NODE_CDATA);
	printf("    | nodeTypeFromInt %i = NodeComment\n", GUMBO_NODE_COMMENT);
	printf("    | nodeTypeFromInt %i = NodeWhitespace\n", GUMBO_NODE_WHITESPACE);
	printf("    | nodeTypeFromInt %i = NodeTemplate\n", GUMBO_NODE_TEMPLATE);
	printf("    | nodeTypeFromInt _ = raise Gumbo \"nodeTypeFromInt\"\n");
	printf("  fun tagTypeFromInt %i = TagHtml\n", GUMBO_TAG_HTML);
	printf("    | tagTypeFromInt %i = TagHead\n", GUMBO_TAG_HEAD);
	printf("    | tagTypeFromInt %i = TagTitle\n", GUMBO_TAG_TITLE);
	printf("    | tagTypeFromInt %i = TagBase\n", GUMBO_TAG_BASE);
	printf("    | tagTypeFromInt %i = TagLink\n", GUMBO_TAG_LINK);
	printf("    | tagTypeFromInt %i = TagMeta\n", GUMBO_TAG_META);
	printf("    | tagTypeFromInt %i = TagStyle\n", GUMBO_TAG_STYLE);
	printf("    | tagTypeFromInt %i = TagScript\n", GUMBO_TAG_SCRIPT);
	printf("    | tagTypeFromInt %i = TagNoscript\n", GUMBO_TAG_NOSCRIPT);
	printf("    | tagTypeFromInt %i = TagTemplate\n", GUMBO_TAG_TEMPLATE);
	printf("    | tagTypeFromInt %i = TagBody\n", GUMBO_TAG_BODY);
	printf("    | tagTypeFromInt %i = TagArticle\n", GUMBO_TAG_ARTICLE);
	printf("    | tagTypeFromInt %i = TagSection\n", GUMBO_TAG_SECTION);
	printf("    | tagTypeFromInt %i = TagNav\n", GUMBO_TAG_NAV);
	printf("    | tagTypeFromInt %i = TagAside\n", GUMBO_TAG_ASIDE);
	printf("    | tagTypeFromInt %i = TagH1\n", GUMBO_TAG_H1);
	printf("    | tagTypeFromInt %i = TagH2\n", GUMBO_TAG_H2);
	printf("    | tagTypeFromInt %i = TagH3\n", GUMBO_TAG_H3);
	printf("    | tagTypeFromInt %i = TagH4\n", GUMBO_TAG_H4);
	printf("    | tagTypeFromInt %i = TagH5\n", GUMBO_TAG_H5);
	printf("    | tagTypeFromInt %i = TagH6\n", GUMBO_TAG_H6);
	printf("    | tagTypeFromInt %i = TagHgroup\n", GUMBO_TAG_HGROUP);
	printf("    | tagTypeFromInt %i = TagHeader\n", GUMBO_TAG_HEADER);
	printf("    | tagTypeFromInt %i = TagFooter\n", GUMBO_TAG_FOOTER);
	printf("    | tagTypeFromInt %i = TagAddress\n", GUMBO_TAG_ADDRESS);
	printf("    | tagTypeFromInt %i = TagP\n", GUMBO_TAG_P);
	printf("    | tagTypeFromInt %i = TagHr\n", GUMBO_TAG_HR);
	printf("    | tagTypeFromInt %i = TagPre\n", GUMBO_TAG_PRE);
	printf("    | tagTypeFromInt %i = TagBlockquote\n", GUMBO_TAG_BLOCKQUOTE);
	printf("    | tagTypeFromInt %i = TagOl\n", GUMBO_TAG_OL);
	printf("    | tagTypeFromInt %i = TagUl\n", GUMBO_TAG_UL);
	printf("    | tagTypeFromInt %i = TagLi\n", GUMBO_TAG_LI);
	printf("    | tagTypeFromInt %i = TagDl\n", GUMBO_TAG_DL);
	printf("    | tagTypeFromInt %i = TagDt\n", GUMBO_TAG_DT);
	printf("    | tagTypeFromInt %i = TagDd\n", GUMBO_TAG_DD);
	printf("    | tagTypeFromInt %i = TagFigure\n", GUMBO_TAG_FIGURE);
	printf("    | tagTypeFromInt %i = TagFigcaption\n", GUMBO_TAG_FIGCAPTION);
	printf("    | tagTypeFromInt %i = TagMain\n", GUMBO_TAG_MAIN);
	printf("    | tagTypeFromInt %i = TagDiv\n", GUMBO_TAG_DIV);
	printf("    | tagTypeFromInt %i = TagA\n", GUMBO_TAG_A);
	printf("    | tagTypeFromInt %i = TagEm\n", GUMBO_TAG_EM);
	printf("    | tagTypeFromInt %i = TagStrong\n", GUMBO_TAG_STRONG);
	printf("    | tagTypeFromInt %i = TagSmall\n", GUMBO_TAG_SMALL);
	printf("    | tagTypeFromInt %i = TagS\n", GUMBO_TAG_S);
	printf("    | tagTypeFromInt %i = TagCite\n", GUMBO_TAG_CITE);
	printf("    | tagTypeFromInt %i = TagQ\n", GUMBO_TAG_Q);
	printf("    | tagTypeFromInt %i = TagDfn\n", GUMBO_TAG_DFN);
	printf("    | tagTypeFromInt %i = TagAbbr\n", GUMBO_TAG_ABBR);
	printf("    | tagTypeFromInt %i = TagData\n", GUMBO_TAG_DATA);
	printf("    | tagTypeFromInt %i = TagTime\n", GUMBO_TAG_TIME);
	printf("    | tagTypeFromInt %i = TagCode\n", GUMBO_TAG_CODE);
	printf("    | tagTypeFromInt %i = TagVar\n", GUMBO_TAG_VAR);
	printf("    | tagTypeFromInt %i = TagSamp\n", GUMBO_TAG_SAMP);
	printf("    | tagTypeFromInt %i = TagKbd\n", GUMBO_TAG_KBD);
	printf("    | tagTypeFromInt %i = TagSub\n", GUMBO_TAG_SUB);
	printf("    | tagTypeFromInt %i = TagSup\n", GUMBO_TAG_SUP);
	printf("    | tagTypeFromInt %i = TagI\n", GUMBO_TAG_I);
	printf("    | tagTypeFromInt %i = TagB\n", GUMBO_TAG_B);
	printf("    | tagTypeFromInt %i = TagU\n", GUMBO_TAG_U);
	printf("    | tagTypeFromInt %i = TagMark\n", GUMBO_TAG_MARK);
	printf("    | tagTypeFromInt %i = TagRuby\n", GUMBO_TAG_RUBY);
	printf("    | tagTypeFromInt %i = TagRt\n", GUMBO_TAG_RT);
	printf("    | tagTypeFromInt %i = TagRp\n", GUMBO_TAG_RP);
	printf("    | tagTypeFromInt %i = TagBdi\n", GUMBO_TAG_BDI);
	printf("    | tagTypeFromInt %i = TagBdo\n", GUMBO_TAG_BDO);
	printf("    | tagTypeFromInt %i = TagSpan\n", GUMBO_TAG_SPAN);
	printf("    | tagTypeFromInt %i = TagBr\n", GUMBO_TAG_BR);
	printf("    | tagTypeFromInt %i = TagWbr\n", GUMBO_TAG_WBR);
	printf("    | tagTypeFromInt %i = TagIns\n", GUMBO_TAG_INS);
	printf("    | tagTypeFromInt %i = TagDel\n", GUMBO_TAG_DEL);
	printf("    | tagTypeFromInt %i = TagImage\n", GUMBO_TAG_IMAGE);
	printf("    | tagTypeFromInt %i = TagImg\n", GUMBO_TAG_IMG);
	printf("    | tagTypeFromInt %i = TagIframe\n", GUMBO_TAG_IFRAME);
	printf("    | tagTypeFromInt %i = TagEmbed\n", GUMBO_TAG_EMBED);
	printf("    | tagTypeFromInt %i = TagObject\n", GUMBO_TAG_OBJECT);
	printf("    | tagTypeFromInt %i = TagParam\n", GUMBO_TAG_PARAM);
	printf("    | tagTypeFromInt %i = TagVideo\n", GUMBO_TAG_VIDEO);
	printf("    | tagTypeFromInt %i = TagAudio\n", GUMBO_TAG_AUDIO);
	printf("    | tagTypeFromInt %i = TagSource\n", GUMBO_TAG_SOURCE);
	printf("    | tagTypeFromInt %i = TagTrack\n", GUMBO_TAG_TRACK);
	printf("    | tagTypeFromInt %i = TagCanvas\n", GUMBO_TAG_CANVAS);
	printf("    | tagTypeFromInt %i = TagMap\n", GUMBO_TAG_MAP);
	printf("    | tagTypeFromInt %i = TagArea\n", GUMBO_TAG_AREA);
	printf("    | tagTypeFromInt %i = TagMath\n", GUMBO_TAG_MATH);
	printf("    | tagTypeFromInt %i = TagMi\n", GUMBO_TAG_MI);
	printf("    | tagTypeFromInt %i = TagMo\n", GUMBO_TAG_MO);
	printf("    | tagTypeFromInt %i = TagMn\n", GUMBO_TAG_MN);
	printf("    | tagTypeFromInt %i = TagMs\n", GUMBO_TAG_MS);
	printf("    | tagTypeFromInt %i = TagMtext\n", GUMBO_TAG_MTEXT);
	printf("    | tagTypeFromInt %i = TagMglyph\n", GUMBO_TAG_MGLYPH);
	printf("    | tagTypeFromInt %i = TagMalignmark\n", GUMBO_TAG_MALIGNMARK);
	printf("    | tagTypeFromInt %i = TagAnnotationXml\n", GUMBO_TAG_ANNOTATION_XML);
	printf("    | tagTypeFromInt %i = TagSvg\n", GUMBO_TAG_SVG);
	printf("    | tagTypeFromInt %i = TagForeignobject\n", GUMBO_TAG_FOREIGNOBJECT);
	printf("    | tagTypeFromInt %i = TagDesc\n", GUMBO_TAG_DESC);
	printf("    | tagTypeFromInt %i = TagTable\n", GUMBO_TAG_TABLE);
	printf("    | tagTypeFromInt %i = TagCaption\n", GUMBO_TAG_CAPTION);
	printf("    | tagTypeFromInt %i = TagColgroup\n", GUMBO_TAG_COLGROUP);
	printf("    | tagTypeFromInt %i = TagCol\n", GUMBO_TAG_COL);
	printf("    | tagTypeFromInt %i = TagTbody\n", GUMBO_TAG_TBODY);
	printf("    | tagTypeFromInt %i = TagThead\n", GUMBO_TAG_THEAD);
	printf("    | tagTypeFromInt %i = TagTfoot\n", GUMBO_TAG_TFOOT);
	printf("    | tagTypeFromInt %i = TagTr\n", GUMBO_TAG_TR);
	printf("    | tagTypeFromInt %i = TagTd\n", GUMBO_TAG_TD);
	printf("    | tagTypeFromInt %i = TagTh\n", GUMBO_TAG_TH);
	printf("    | tagTypeFromInt %i = TagForm\n", GUMBO_TAG_FORM);
	printf("    | tagTypeFromInt %i = TagFieldset\n", GUMBO_TAG_FIELDSET);
	printf("    | tagTypeFromInt %i = TagLegend\n", GUMBO_TAG_LEGEND);
	printf("    | tagTypeFromInt %i = TagLabel\n", GUMBO_TAG_LABEL);
	printf("    | tagTypeFromInt %i = TagInput\n", GUMBO_TAG_INPUT);
	printf("    | tagTypeFromInt %i = TagButton\n", GUMBO_TAG_BUTTON);
	printf("    | tagTypeFromInt %i = TagSelect\n", GUMBO_TAG_SELECT);
	printf("    | tagTypeFromInt %i = TagDatalist\n", GUMBO_TAG_DATALIST);
	printf("    | tagTypeFromInt %i = TagOptgroup\n", GUMBO_TAG_OPTGROUP);
	printf("    | tagTypeFromInt %i = TagOption\n", GUMBO_TAG_OPTION);
	printf("    | tagTypeFromInt %i = TagTextarea\n", GUMBO_TAG_TEXTAREA);
	printf("    | tagTypeFromInt %i = TagKeygen\n", GUMBO_TAG_KEYGEN);
	printf("    | tagTypeFromInt %i = TagOutput\n", GUMBO_TAG_OUTPUT);
	printf("    | tagTypeFromInt %i = TagProgress\n", GUMBO_TAG_PROGRESS);
	printf("    | tagTypeFromInt %i = TagMeter\n", GUMBO_TAG_METER);
	printf("    | tagTypeFromInt %i = TagDetails\n", GUMBO_TAG_DETAILS);
	printf("    | tagTypeFromInt %i = TagSummary\n", GUMBO_TAG_SUMMARY);
	printf("    | tagTypeFromInt %i = TagMenu\n", GUMBO_TAG_MENU);
	printf("    | tagTypeFromInt %i = TagMenuitem\n", GUMBO_TAG_MENUITEM);
	printf("    | tagTypeFromInt %i = TagApplet\n", GUMBO_TAG_APPLET);
	printf("    | tagTypeFromInt %i = TagAcronym\n", GUMBO_TAG_ACRONYM);
	printf("    | tagTypeFromInt %i = TagBgsound\n", GUMBO_TAG_BGSOUND);
	printf("    | tagTypeFromInt %i = TagDir\n", GUMBO_TAG_DIR);
	printf("    | tagTypeFromInt %i = TagFrame\n", GUMBO_TAG_FRAME);
	printf("    | tagTypeFromInt %i = TagFrameset\n", GUMBO_TAG_FRAMESET);
	printf("    | tagTypeFromInt %i = TagNoframes\n", GUMBO_TAG_NOFRAMES);
	printf("    | tagTypeFromInt %i = TagIsindex\n", GUMBO_TAG_ISINDEX);
	printf("    | tagTypeFromInt %i = TagListing\n", GUMBO_TAG_LISTING);
	printf("    | tagTypeFromInt %i = TagXmp\n", GUMBO_TAG_XMP);
	printf("    | tagTypeFromInt %i = TagNextid\n", GUMBO_TAG_NEXTID);
	printf("    | tagTypeFromInt %i = TagNoembed\n", GUMBO_TAG_NOEMBED);
	printf("    | tagTypeFromInt %i = TagPlaintext\n", GUMBO_TAG_PLAINTEXT);
	printf("    | tagTypeFromInt %i = TagRb\n", GUMBO_TAG_RB);
	printf("    | tagTypeFromInt %i = TagStrike\n", GUMBO_TAG_STRIKE);
	printf("    | tagTypeFromInt %i = TagBasefont\n", GUMBO_TAG_BASEFONT);
	printf("    | tagTypeFromInt %i = TagBig\n", GUMBO_TAG_BIG);
	printf("    | tagTypeFromInt %i = TagBlink\n", GUMBO_TAG_BLINK);
	printf("    | tagTypeFromInt %i = TagCenter\n", GUMBO_TAG_CENTER);
	printf("    | tagTypeFromInt %i = TagFont\n", GUMBO_TAG_FONT);
	printf("    | tagTypeFromInt %i = TagMarquee\n", GUMBO_TAG_MARQUEE);
	printf("    | tagTypeFromInt %i = TagMulticol\n", GUMBO_TAG_MULTICOL);
	printf("    | tagTypeFromInt %i = TagNobr\n", GUMBO_TAG_NOBR);
	printf("    | tagTypeFromInt %i = TagSpacer\n", GUMBO_TAG_SPACER);
	printf("    | tagTypeFromInt %i = TagTt\n", GUMBO_TAG_TT);
	printf("    | tagTypeFromInt %i = TagRtc\n", GUMBO_TAG_RTC);
	printf("    | tagTypeFromInt %i = TagUnknown\n", GUMBO_TAG_UNKNOWN);
	printf("    | tagTypeFromInt %i = TagLast\n", GUMBO_TAG_LAST);
	printf("    | tagTypeFromInt _ = raise Gumbo \"tagTypeFromInt\"\n");

	printf("end\n");

	// printf("\n(*\n");
	// printf("  val sizeof_GumboNodeType = %zu\n", sizeof(GumboNodeType));
	// printf("*)\n");

	return 0;
}
