// Generated, do not edit.
#include <stdio.h>
#include <stddef.h>
#include "gumbo.h"

int main () {
	printf("(* Generated, do not edit. *)\n");
	printf("structure GumboConstants =\n");
	printf("struct\n");
	printf("  open GumboCommon\n");

	printf("  val offsetof_ActualNodeData = %zu\n", offsetof(struct GumboInternalNode, v));
	printf("  val offsetof_ElementTag = %zu\n", offsetof(GumboElement, tag));
	printf("  val offsetof_ElementAttributes = %zu\n", offsetof(GumboElement, attributes));
	printf("  val offsetof_GumboAttributeName = %zu\n", offsetof(GumboAttribute, name));
	printf("  val offsetof_GumboAttributeValue = %zu\n", offsetof(GumboAttribute, value));

	printf("  fun nodeTypeFromInt %zi = NodeDocument\n", GUMBO_NODE_DOCUMENT);
	printf("    | nodeTypeFromInt %zi = NodeElement\n", GUMBO_NODE_ELEMENT);
	printf("    | nodeTypeFromInt %zi = NodeText\n", GUMBO_NODE_TEXT);
	printf("    | nodeTypeFromInt %zi = NodeCdata\n", GUMBO_NODE_CDATA);
	printf("    | nodeTypeFromInt %zi = NodeComment\n", GUMBO_NODE_COMMENT);
	printf("    | nodeTypeFromInt %zi = NodeWhitespace\n", GUMBO_NODE_WHITESPACE);
	printf("    | nodeTypeFromInt %zi = NodeTemplate\n", GUMBO_NODE_TEMPLATE);
	printf("    | nodeTypeFromInt _ = raise Gumbo \"nodeTypeFromInt\"\n");
	printf("  fun tagTypeFromInt %zi = TagHtml\n", GUMBO_TAG_HTML);
	printf("    | tagTypeFromInt %zi = TagHead\n", GUMBO_TAG_HEAD);
	printf("    | tagTypeFromInt %zi = TagTitle\n", GUMBO_TAG_TITLE);
	printf("    | tagTypeFromInt %zi = TagBase\n", GUMBO_TAG_BASE);
	printf("    | tagTypeFromInt %zi = TagLink\n", GUMBO_TAG_LINK);
	printf("    | tagTypeFromInt %zi = TagMeta\n", GUMBO_TAG_META);
	printf("    | tagTypeFromInt %zi = TagStyle\n", GUMBO_TAG_STYLE);
	printf("    | tagTypeFromInt %zi = TagScript\n", GUMBO_TAG_SCRIPT);
	printf("    | tagTypeFromInt %zi = TagNoscript\n", GUMBO_TAG_NOSCRIPT);
	printf("    | tagTypeFromInt %zi = TagTemplate\n", GUMBO_TAG_TEMPLATE);
	printf("    | tagTypeFromInt %zi = TagBody\n", GUMBO_TAG_BODY);
	printf("    | tagTypeFromInt %zi = TagArticle\n", GUMBO_TAG_ARTICLE);
	printf("    | tagTypeFromInt %zi = TagSection\n", GUMBO_TAG_SECTION);
	printf("    | tagTypeFromInt %zi = TagNav\n", GUMBO_TAG_NAV);
	printf("    | tagTypeFromInt %zi = TagAside\n", GUMBO_TAG_ASIDE);
	printf("    | tagTypeFromInt %zi = TagH1\n", GUMBO_TAG_H1);
	printf("    | tagTypeFromInt %zi = TagH2\n", GUMBO_TAG_H2);
	printf("    | tagTypeFromInt %zi = TagH3\n", GUMBO_TAG_H3);
	printf("    | tagTypeFromInt %zi = TagH4\n", GUMBO_TAG_H4);
	printf("    | tagTypeFromInt %zi = TagH5\n", GUMBO_TAG_H5);
	printf("    | tagTypeFromInt %zi = TagH6\n", GUMBO_TAG_H6);
	printf("    | tagTypeFromInt %zi = TagHgroup\n", GUMBO_TAG_HGROUP);
	printf("    | tagTypeFromInt %zi = TagHeader\n", GUMBO_TAG_HEADER);
	printf("    | tagTypeFromInt %zi = TagFooter\n", GUMBO_TAG_FOOTER);
	printf("    | tagTypeFromInt %zi = TagAddress\n", GUMBO_TAG_ADDRESS);
	printf("    | tagTypeFromInt %zi = TagP\n", GUMBO_TAG_P);
	printf("    | tagTypeFromInt %zi = TagHr\n", GUMBO_TAG_HR);
	printf("    | tagTypeFromInt %zi = TagPre\n", GUMBO_TAG_PRE);
	printf("    | tagTypeFromInt %zi = TagBlockquote\n", GUMBO_TAG_BLOCKQUOTE);
	printf("    | tagTypeFromInt %zi = TagOl\n", GUMBO_TAG_OL);
	printf("    | tagTypeFromInt %zi = TagUl\n", GUMBO_TAG_UL);
	printf("    | tagTypeFromInt %zi = TagLi\n", GUMBO_TAG_LI);
	printf("    | tagTypeFromInt %zi = TagDl\n", GUMBO_TAG_DL);
	printf("    | tagTypeFromInt %zi = TagDt\n", GUMBO_TAG_DT);
	printf("    | tagTypeFromInt %zi = TagDd\n", GUMBO_TAG_DD);
	printf("    | tagTypeFromInt %zi = TagFigure\n", GUMBO_TAG_FIGURE);
	printf("    | tagTypeFromInt %zi = TagFigcaption\n", GUMBO_TAG_FIGCAPTION);
	printf("    | tagTypeFromInt %zi = TagMain\n", GUMBO_TAG_MAIN);
	printf("    | tagTypeFromInt %zi = TagDiv\n", GUMBO_TAG_DIV);
	printf("    | tagTypeFromInt %zi = TagA\n", GUMBO_TAG_A);
	printf("    | tagTypeFromInt %zi = TagEm\n", GUMBO_TAG_EM);
	printf("    | tagTypeFromInt %zi = TagStrong\n", GUMBO_TAG_STRONG);
	printf("    | tagTypeFromInt %zi = TagSmall\n", GUMBO_TAG_SMALL);
	printf("    | tagTypeFromInt %zi = TagS\n", GUMBO_TAG_S);
	printf("    | tagTypeFromInt %zi = TagCite\n", GUMBO_TAG_CITE);
	printf("    | tagTypeFromInt %zi = TagQ\n", GUMBO_TAG_Q);
	printf("    | tagTypeFromInt %zi = TagDfn\n", GUMBO_TAG_DFN);
	printf("    | tagTypeFromInt %zi = TagAbbr\n", GUMBO_TAG_ABBR);
	printf("    | tagTypeFromInt %zi = TagData\n", GUMBO_TAG_DATA);
	printf("    | tagTypeFromInt %zi = TagTime\n", GUMBO_TAG_TIME);
	printf("    | tagTypeFromInt %zi = TagCode\n", GUMBO_TAG_CODE);
	printf("    | tagTypeFromInt %zi = TagVar\n", GUMBO_TAG_VAR);
	printf("    | tagTypeFromInt %zi = TagSamp\n", GUMBO_TAG_SAMP);
	printf("    | tagTypeFromInt %zi = TagKbd\n", GUMBO_TAG_KBD);
	printf("    | tagTypeFromInt %zi = TagSub\n", GUMBO_TAG_SUB);
	printf("    | tagTypeFromInt %zi = TagSup\n", GUMBO_TAG_SUP);
	printf("    | tagTypeFromInt %zi = TagI\n", GUMBO_TAG_I);
	printf("    | tagTypeFromInt %zi = TagB\n", GUMBO_TAG_B);
	printf("    | tagTypeFromInt %zi = TagU\n", GUMBO_TAG_U);
	printf("    | tagTypeFromInt %zi = TagMark\n", GUMBO_TAG_MARK);
	printf("    | tagTypeFromInt %zi = TagRuby\n", GUMBO_TAG_RUBY);
	printf("    | tagTypeFromInt %zi = TagRt\n", GUMBO_TAG_RT);
	printf("    | tagTypeFromInt %zi = TagRp\n", GUMBO_TAG_RP);
	printf("    | tagTypeFromInt %zi = TagBdi\n", GUMBO_TAG_BDI);
	printf("    | tagTypeFromInt %zi = TagBdo\n", GUMBO_TAG_BDO);
	printf("    | tagTypeFromInt %zi = TagSpan\n", GUMBO_TAG_SPAN);
	printf("    | tagTypeFromInt %zi = TagBr\n", GUMBO_TAG_BR);
	printf("    | tagTypeFromInt %zi = TagWbr\n", GUMBO_TAG_WBR);
	printf("    | tagTypeFromInt %zi = TagIns\n", GUMBO_TAG_INS);
	printf("    | tagTypeFromInt %zi = TagDel\n", GUMBO_TAG_DEL);
	printf("    | tagTypeFromInt %zi = TagImage\n", GUMBO_TAG_IMAGE);
	printf("    | tagTypeFromInt %zi = TagImg\n", GUMBO_TAG_IMG);
	printf("    | tagTypeFromInt %zi = TagIframe\n", GUMBO_TAG_IFRAME);
	printf("    | tagTypeFromInt %zi = TagEmbed\n", GUMBO_TAG_EMBED);
	printf("    | tagTypeFromInt %zi = TagObject\n", GUMBO_TAG_OBJECT);
	printf("    | tagTypeFromInt %zi = TagParam\n", GUMBO_TAG_PARAM);
	printf("    | tagTypeFromInt %zi = TagVideo\n", GUMBO_TAG_VIDEO);
	printf("    | tagTypeFromInt %zi = TagAudio\n", GUMBO_TAG_AUDIO);
	printf("    | tagTypeFromInt %zi = TagSource\n", GUMBO_TAG_SOURCE);
	printf("    | tagTypeFromInt %zi = TagTrack\n", GUMBO_TAG_TRACK);
	printf("    | tagTypeFromInt %zi = TagCanvas\n", GUMBO_TAG_CANVAS);
	printf("    | tagTypeFromInt %zi = TagMap\n", GUMBO_TAG_MAP);
	printf("    | tagTypeFromInt %zi = TagArea\n", GUMBO_TAG_AREA);
	printf("    | tagTypeFromInt %zi = TagMath\n", GUMBO_TAG_MATH);
	printf("    | tagTypeFromInt %zi = TagMi\n", GUMBO_TAG_MI);
	printf("    | tagTypeFromInt %zi = TagMo\n", GUMBO_TAG_MO);
	printf("    | tagTypeFromInt %zi = TagMn\n", GUMBO_TAG_MN);
	printf("    | tagTypeFromInt %zi = TagMs\n", GUMBO_TAG_MS);
	printf("    | tagTypeFromInt %zi = TagMtext\n", GUMBO_TAG_MTEXT);
	printf("    | tagTypeFromInt %zi = TagMglyph\n", GUMBO_TAG_MGLYPH);
	printf("    | tagTypeFromInt %zi = TagMalignmark\n", GUMBO_TAG_MALIGNMARK);
	printf("    | tagTypeFromInt %zi = TagAnnotationXml\n", GUMBO_TAG_ANNOTATION_XML);
	printf("    | tagTypeFromInt %zi = TagSvg\n", GUMBO_TAG_SVG);
	printf("    | tagTypeFromInt %zi = TagForeignobject\n", GUMBO_TAG_FOREIGNOBJECT);
	printf("    | tagTypeFromInt %zi = TagDesc\n", GUMBO_TAG_DESC);
	printf("    | tagTypeFromInt %zi = TagTable\n", GUMBO_TAG_TABLE);
	printf("    | tagTypeFromInt %zi = TagCaption\n", GUMBO_TAG_CAPTION);
	printf("    | tagTypeFromInt %zi = TagColgroup\n", GUMBO_TAG_COLGROUP);
	printf("    | tagTypeFromInt %zi = TagCol\n", GUMBO_TAG_COL);
	printf("    | tagTypeFromInt %zi = TagTbody\n", GUMBO_TAG_TBODY);
	printf("    | tagTypeFromInt %zi = TagThead\n", GUMBO_TAG_THEAD);
	printf("    | tagTypeFromInt %zi = TagTfoot\n", GUMBO_TAG_TFOOT);
	printf("    | tagTypeFromInt %zi = TagTr\n", GUMBO_TAG_TR);
	printf("    | tagTypeFromInt %zi = TagTd\n", GUMBO_TAG_TD);
	printf("    | tagTypeFromInt %zi = TagTh\n", GUMBO_TAG_TH);
	printf("    | tagTypeFromInt %zi = TagForm\n", GUMBO_TAG_FORM);
	printf("    | tagTypeFromInt %zi = TagFieldset\n", GUMBO_TAG_FIELDSET);
	printf("    | tagTypeFromInt %zi = TagLegend\n", GUMBO_TAG_LEGEND);
	printf("    | tagTypeFromInt %zi = TagLabel\n", GUMBO_TAG_LABEL);
	printf("    | tagTypeFromInt %zi = TagInput\n", GUMBO_TAG_INPUT);
	printf("    | tagTypeFromInt %zi = TagButton\n", GUMBO_TAG_BUTTON);
	printf("    | tagTypeFromInt %zi = TagSelect\n", GUMBO_TAG_SELECT);
	printf("    | tagTypeFromInt %zi = TagDatalist\n", GUMBO_TAG_DATALIST);
	printf("    | tagTypeFromInt %zi = TagOptgroup\n", GUMBO_TAG_OPTGROUP);
	printf("    | tagTypeFromInt %zi = TagOption\n", GUMBO_TAG_OPTION);
	printf("    | tagTypeFromInt %zi = TagTextarea\n", GUMBO_TAG_TEXTAREA);
	printf("    | tagTypeFromInt %zi = TagKeygen\n", GUMBO_TAG_KEYGEN);
	printf("    | tagTypeFromInt %zi = TagOutput\n", GUMBO_TAG_OUTPUT);
	printf("    | tagTypeFromInt %zi = TagProgress\n", GUMBO_TAG_PROGRESS);
	printf("    | tagTypeFromInt %zi = TagMeter\n", GUMBO_TAG_METER);
	printf("    | tagTypeFromInt %zi = TagDetails\n", GUMBO_TAG_DETAILS);
	printf("    | tagTypeFromInt %zi = TagSummary\n", GUMBO_TAG_SUMMARY);
	printf("    | tagTypeFromInt %zi = TagMenu\n", GUMBO_TAG_MENU);
	printf("    | tagTypeFromInt %zi = TagMenuitem\n", GUMBO_TAG_MENUITEM);
	printf("    | tagTypeFromInt %zi = TagApplet\n", GUMBO_TAG_APPLET);
	printf("    | tagTypeFromInt %zi = TagAcronym\n", GUMBO_TAG_ACRONYM);
	printf("    | tagTypeFromInt %zi = TagBgsound\n", GUMBO_TAG_BGSOUND);
	printf("    | tagTypeFromInt %zi = TagDir\n", GUMBO_TAG_DIR);
	printf("    | tagTypeFromInt %zi = TagFrame\n", GUMBO_TAG_FRAME);
	printf("    | tagTypeFromInt %zi = TagFrameset\n", GUMBO_TAG_FRAMESET);
	printf("    | tagTypeFromInt %zi = TagNoframes\n", GUMBO_TAG_NOFRAMES);
	printf("    | tagTypeFromInt %zi = TagIsindex\n", GUMBO_TAG_ISINDEX);
	printf("    | tagTypeFromInt %zi = TagListing\n", GUMBO_TAG_LISTING);
	printf("    | tagTypeFromInt %zi = TagXmp\n", GUMBO_TAG_XMP);
	printf("    | tagTypeFromInt %zi = TagNextid\n", GUMBO_TAG_NEXTID);
	printf("    | tagTypeFromInt %zi = TagNoembed\n", GUMBO_TAG_NOEMBED);
	printf("    | tagTypeFromInt %zi = TagPlaintext\n", GUMBO_TAG_PLAINTEXT);
	printf("    | tagTypeFromInt %zi = TagRb\n", GUMBO_TAG_RB);
	printf("    | tagTypeFromInt %zi = TagStrike\n", GUMBO_TAG_STRIKE);
	printf("    | tagTypeFromInt %zi = TagBasefont\n", GUMBO_TAG_BASEFONT);
	printf("    | tagTypeFromInt %zi = TagBig\n", GUMBO_TAG_BIG);
	printf("    | tagTypeFromInt %zi = TagBlink\n", GUMBO_TAG_BLINK);
	printf("    | tagTypeFromInt %zi = TagCenter\n", GUMBO_TAG_CENTER);
	printf("    | tagTypeFromInt %zi = TagFont\n", GUMBO_TAG_FONT);
	printf("    | tagTypeFromInt %zi = TagMarquee\n", GUMBO_TAG_MARQUEE);
	printf("    | tagTypeFromInt %zi = TagMulticol\n", GUMBO_TAG_MULTICOL);
	printf("    | tagTypeFromInt %zi = TagNobr\n", GUMBO_TAG_NOBR);
	printf("    | tagTypeFromInt %zi = TagSpacer\n", GUMBO_TAG_SPACER);
	printf("    | tagTypeFromInt %zi = TagTt\n", GUMBO_TAG_TT);
	printf("    | tagTypeFromInt %zi = TagRtc\n", GUMBO_TAG_RTC);
	printf("    | tagTypeFromInt %zi = TagUnknown\n", GUMBO_TAG_UNKNOWN);
	printf("    | tagTypeFromInt %zi = TagLast\n", GUMBO_TAG_LAST);
	printf("    | tagTypeFromInt _ = raise Gumbo \"tagTypeFromInt\"\n");

	printf("end\n");

	// printf("\n(*\n");
	// printf("  val sizeof_GumboNodeType = %zu\n", sizeof(GumboNodeType));
	// printf("*)\n");

	return 0;
}
